services:
  monster1:
    hostname: monster1
    image: rocworks/monstermq:testing
    restart: always
    ports:
      - "11883:1883"
      - "11884:1884"
      - "14000:4000"
      - "13001:3001"
      - "13002:3002"
      - "13003:3003"
    environment:
      - HAZELCAST_CONFIG=hazelcast.xml
    command: ["-cluster"]
    volumes:
      - ./security:/app/security
      - ./monster.yml:/app/config.yaml

  monster2:
    hostname: monster2
    image: rocworks/monstermq:testing
    restart: always
    ports:
      - "21883:1883"
      - "21884:1884"
      - "24000:4000"
      - "23001:3001"
      - "23002:3002"
      - "23003:3003"  
    environment:
      - HAZELCAST_CONFIG=hazelcast.xml^
    command: ["-cluster"]
    volumes:
      - ./security:/app/security
      - ./monster.yml:/app/config.yaml

  monster3:
    hostname: monster3
    image: rocworks/monstermq:testing
    restart: always
    ports:
      - "31883:1883"
      - "31884:1884"
      - "34000:4000"
      - "33001:3001"
      - "33002:3002"
      - "33003:3003"    
    environment:
      - HAZELCAST_CONFIG=hazelcast.xml
    command: ["-cluster"]
    volumes:
      - ./security:/app/security
      - ./monster.yml:/app/config.yaml
