TCP: 1883
WS: 1884

QueuedMessagesEnabled: true

DefaultStoreType: POSTGRES

Logging:
  Mqtt:
    Enabled: false
  Memory:
    Enabled: true
    Entries: 2000

Postgres:
  Url: jdbc:postgresql://192.168.1.35:5432/monster-cluster
  User: system
  Pass: manager
  Schema: public
