TCP: 1883
TPCS: 8883
WS: 9000
WSS: 9001

MaxMessageSizeKb: 512
QueuedMessagesEnabled: true

SessionStoreType: SQLITE
RetainedStoreType: SQLITE

SparkplugMetricExpansion:
  Enabled: true

ArchiveGroups:
  - Name: Default
    Enabled: true
    TopicFilter: [ "#" ]
    RetainedOnly: false
    LastValType: SQLITE
    ArchiveType: SQLITE
    LastValRetention: "60m"
    ArchiveRetention: "30d"
    PurgeInterval: "1m"

SQLite:
  Path: "monstermq.db"      
  
MCP:
  Enabled: true
  Port: 3000

GraphQL:
  Enabled: true
  Port: 4000
  Path: /graphql
