TCP: 1883
TPCS: 8883
WS: 9000
WSS: 9001

MaxMessageSizeKb: 512
QueuedMessagesEnabled: true

SessionStoreType: POSTGRES
RetainedStoreType: POSTGRES

SparkplugMetricExpansion:
  Enabled: true

ArchiveGroups:
  - Name: Default
    Enabled: true
    TopicFilter: [ "#" ]
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES
    LastValRetention: "60m"
    ArchiveRetention: "30d"
    PurgeInterval: "1m"

# PostgreSQL configuration
Postgres:
  Url: jdbc:postgresql://database:5432/monster
  User: system
  Pass: manager

# MCP Server configuration
MCP:
  Enabled: true
  Port: 3000

GraphQL:
  Enabled: true
  Port: 4000
  Path: /graphql
  CorsEnabled: false
  CorsOrigin: "*"