Port: 1883
SSL: false
WS: false
TCP: true

SessionStoreType: POSTGRES

SparkplugMetricExpansion:
  Enabled: true

RetainedMessages:
  StoreType: POSTGRES
  ArchiveType: NONE

LastValueMessages:
  TopicFilter: [  ]
  StoreType: POSTGRES
  ArchiveType: POSTGRES

Kafka:
  Enabled: false
  Servers: linux0:9092
  Topic: monster

Postgres:
  Url: jdbc:postgresql://192.168.1.30:5432/postgres
  User: system
  Pass: manager
