TCP: 1883
TPCS: 8883
WS: 9000
WSS: 9001

MaxMessageSizeKb: 512
QueuedMessagesEnabled: true

SessionStoreType: SQLITE
RetainedStoreType: SQLITE

SparkplugMetricExpansion:
  Enabled: true

ArchiveGroups:
  - Name: MCP
    Enabled: true
    TopicFilter: [ "#" ]
    RetainedOnly: false
    LastValType: SQLITE
    ArchiveType: SQLITE

# SQLite configuration
SQLite:
  Path: "monstermq.db"

# PostgreSQL configuration
Postgres:
  Url: jdbc:postgresql://linux0:5432/monster
  User: system
  Pass: manager

# CrateDB configuration
CrateDB:
  Url: jdbc:postgresql://linux0:5432/monster
  User: crate
  Pass: ""

# MongoDB configuration
MongoDB:
  Url: mongodb://system:manager@scada:27017
  Database: monster

# Kafka configuration
Kafka:
  Servers: linux0:9092
  Bus: # Use Kafka as the message bus
    Enabled: false
    Topic: monster

# MCP Server configuration
MCP:
  Enabled: true
  Port: 3000