TCP: 1883
WS: 1884
SSL: false
MaxMessageSizeKb: 512
QueuedMessagesEnabled: true

SessionStoreType: POSTGRES
RetainedStoreType: POSTGRES

SparkplugMetricExpansion:
  Enabled: true

ArchiveGroups:
  - Name: "group1"
    Enabled: true
    TopicFilter: [ "test1/#" ]
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES
  - Name: "group2"
    Enabled: true
    TopicFilter: [ "test2/#" ]
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES
  - Name: "video"
    Enabled: false
    TopicFilter: [ "video/#" ]
    RetainedOnly: false
    LastValType: NONE
    ArchiveType: KAFKA

Kafka:
  Servers: linux0:9092
  Bus: # Use Kafka as the message bus
    Enabled: false
    Topic: monster

Postgres:
  Url: jdbc:postgresql://192.168.1.4:5432/monster
  User: system
  Pass: manager

CrateDB:
  Url: jdbc:postgresql://192.168.1.31:5432/test
  User: crate
  Pass: ""
