Port: 1883
SSL: false
WS: false
TCP: true

SessionStoreType: POSTGRES
RetainedStoreType: POSTGRES

SparkplugMetricExpansion:
  Enabled: true

ArchiveGroups:
  - Name: "group1"
    Enabled: true
    TopicFilter: [ "test1/#" ]
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES
  - Name: "group2"
    Enabled: true
    TopicFilter: [ "test2/#" ]
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES

Kafka:
  Enabled: false
  Servers: linux0:9092
  Topic: monster

Postgres:
  Url: jdbc:postgresql://192.168.1.30:5432/postgres
  User: system
  Pass: manager

CrateDB:
  Url: jdbc:postgresql://192.168.1.31:5432/test
  User: crate
  Pass: ""
