Port: 1883
SSL: false
WS: false
TCP: true

SessionStoreType: POSTGRES

RetainedMessageStoreType: POSTGRES
RetainedMessageStoreArch: POSTGRES

LastValueMessageStoreType: POSTGRES
LastValueMessageStoreArch: POSTGRES

#Kafka:
#  Servers: linux0:9092
#  Topic: monster

Postgres:
  Url: jdbc:postgresql://192.168.1.30:5432/postgres
  User: system
  Pass: manager
