TCP: 1883
WS: 9001

MaxMessageSizeKb: 512
QueuedMessagesEnabled: true

SessionStoreType: MONGODB
RetainedStoreType: MONGODB

SparkplugMetricExpansion:
  Enabled: true

ArchiveGroups:
  - Name: "Postgres"
    Enabled: true
    TopicFilter: [ "postgres/#" ]
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES
  - Name: "MongoDB"
    Enabled: true
    TopicFilter: [ "mongodb/#" ]
    RetainedOnly: false
    LastValType: MONGODB
    ArchiveType: MONGODB

Kafka:
  Servers: linux0:9092
  Bus: # Use Kafka as the message bus
    Enabled: false
    Topic: monster

Postgres:
  Url: jdbc:postgresql://scada:5432/test
  User: system
  Pass: manager

CrateDB:
  Url: jdbc:postgresql://scada:5432/test
  User: crate
  Pass: ""

MongoDB:
  Url: mongodb://system:manager@linux0:27017
  Database: test