TCP: 1883
TPCS: 8883
WS: 9000
WSS: 9001

QueuedMessagesEnabled: true
AllowRootWildcardSubscription: true

DefaultStoreType: POSTGRES

# User Management configuration
UserManagement:
  Enabled: false  # Set to true to enable user authentication and ACL
  PasswordAlgorithm: bcrypt
  CacheRefreshInterval: 60  # seconds
  DisconnectOnUnauthorized: true

# MQTT TCP Server configuration (socket-level settings)
MqttTcpServer:
  NoDelay: true                  # TCP_NODELAY - disable Nagle's algorithm for immediate packet transmission
  ReceiveBufferSizeKb: 512       # Socket receive buffer size (default: 512KB, recommended: 512KB-2MB for high load)
  SendBufferSizeKb: 512          # Socket send buffer size (default: 512KB, recommended: 512KB-2MB for high load)
  MaxMessageSizeKb: 512

# Queue size configuration for high-load scenarios
Queues:
  SubscriptionQueueSize: 50000  # Queue size for subscription add/delete operations (default: 10,000)
  MessageQueueSize: 50000       # Queue size for message add/delete operations (default: 10,000)

# Metrics configuration
Logging:
  Mqtt:
    Enabled: true          # Enable MQTT log publishing to $SYS/syslogs/<node>/<level> topics
  Memory:
    Enabled: true         # Enable in-memory log storage (circular buffer)
    Entries: 1000          # Maximum number of log entries to store in memory



# Sparkplug B support configuration
SparkplugMetricExpansion:
  Enabled: true

# SQLite configuration
SQLite:
  Path: "sqlite"

# PostgreSQL configuration
Postgres:
  Url: jdbc:postgresql://linux5:5432/monster
  User: system
  Pass: manager

# CrateDB configuration
CrateDB:
  Url: jdbc:postgresql://linux5:5433/monster
  User: crate
  Pass: ""

# MongoDB configuration
MongoDB:
  Url: mongodb://system:manager@linux5:27017
  Database: monster

# Kafka configuration
Kafka:
  Servers: linux0:9092
  Bus: # Use Kafka as the message bus
    Enabled: false
    Topic: monster

# MCP Server configuration
MCP:
  Enabled: true
  Port: 3000

GraphQL:
  Enabled: true
  Port: 4000
  Path: /graphql

# Archive group examples (import via -archiveConfig or GraphQL mutations)
ArchiveGroups:
  - Name: Default
    Enabled: true
    TopicFilter: ["#"]
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES
    PayloadFormat: DEFAULT
    LastValRetention: "7d"
    ArchiveRetention: "30d"
    PurgeInterval: "1h"
