TCP: 1886

NodeName: "node4"

MaxMessageSizeKb: 512
QueuedMessagesEnabled: true

SessionStoreType: POSTGRES
RetainedStoreType: POSTGRES
ConfigStoreType: POSTGRES

# User Management configuration
UserManagement:
  Enabled: true  # Set to true to enable user authentication and ACL
  AuthStoreType: POSTGRES  # POSTGRES, SQLITE, CRATEDB, MONGODB
  PasswordAlgorithm: bcrypt
  CacheRefreshInterval: 60  # seconds
  DisconnectOnUnauthorized: true

Metrics:
  Enabled: true
  StoreType: POSTGRES  # POSTGRES, CRATEDB, MONGODB
  RetentionHours: 1   # Default 1 day
  CollectionInterval: 10  # Collection interval in seconds (default: 1)

SparkplugMetricExpansion:
  Enabled: true

# SQLite configuration
SQLite:
  Path: "monstermq.db"

# PostgreSQL configuration
Postgres:
  Url: jdbc:postgresql://192.168.1.35:5432/monster
  User: system
  Pass: manager

# CrateDB configuration
CrateDB:
  Url: jdbc:postgresql://192.168.1.35:5433/monster
  User: crate
  Pass: ""

# MongoDB configuration
MongoDB:
  Url: mongodb://system:manager@192.168.1.35:27017
  Database: monster

# Kafka configuration
Kafka:
  Servers: linux0:9092
  Bus: # Use Kafka as the message bus
    Enabled: false
    Topic: monster

# MCP Server configuration
MCP:
  Enabled: false
  Port: 3000

GraphQL:
  Enabled: true
  Port: 4003
  Path: /graphql
