# MonsterMQ Configuration with SQLite Support
TCP: 1883
WS: 8080
MaxMessageSizeKb: 8

# Use SQLite for all storage needs
SessionStoreType: SQLITE
RetainedStoreType: SQLITE
ConfigStoreType: SQLITE

QueuedMessagesEnabled: true

# SQLite configuration
SQLite:
  Path: "sqlite"

# MCP Server configuration
MCP:
  Enabled: true
  Port: 3000

GraphQL:
  Enabled: true
  Port: 4000
  Path: /graphql

Logging:
  Mqtt:
    Enabled: true
  Memory:
    Enabled: false
    Entries: 1000
