# Example configuration with retention settings for ArchiveGroups

TCP: 1883
RetainedStoreType: MEMORY

ArchiveGroups:
  - Name: Default
    Enabled: true
    TopicFilter:
      - "#"
    RetainedOnly: false
    LastValType: MEMORY
    ArchiveType: POSTGRES
    # Retention configuration (optional)
    LastValRetention: "7d"      # Keep last values for 7 days
    ArchiveRetention: "30d"      # Keep archive data for 30 days
    PurgeInterval: "1h"          # Run purge every hour

  - Name: ShortTerm
    Enabled: true
    TopicFilter:
      - "sensors/temperature/#"
      - "sensors/humidity/#"
    RetainedOnly: false
    LastValType: HAZELCAST
    ArchiveType: CRATEDB
    # More aggressive retention for high-frequency sensor data
    LastValRetention: "1d"       # Keep last values for 1 day
    ArchiveRetention: "7d"       # Keep archive data for 7 days
    PurgeInterval: "30m"         # Run purge every 30 minutes

  - Name: LongTerm
    Enabled: true
    TopicFilter:
      - "system/logs/#"
      - "audit/#"
    RetainedOnly: false
    LastValType: POSTGRES
    ArchiveType: POSTGRES
    # Long-term retention for audit/compliance
    LastValRetention: "30d"      # Keep last values for 30 days
    ArchiveRetention: "1y"       # Keep archive data for 1 year
    PurgeInterval: "1d"          # Run purge once per day

# Supported retention period formats:
# s - seconds (e.g., "30s")
# m - minutes (e.g., "15m")
# h - hours (e.g., "12h")
# d - days (e.g., "7d")
# w - weeks (e.g., "4w")
# M - months (e.g., "3M") - approximated as 30 days
# y - years (e.g., "1y") - approximated as 365 days

Postgres:
  Url: "jdbc:postgresql://localhost:5432/monstermq"
  User: "postgres"
  Pass: "password"

CrateDB:
  Url: "jdbc:postgresql://localhost:5432/monstermq"
  User: "crate"
  Pass: ""